---
  #############################
  # Init / Prepare SSH
  #############################

- name: Config sshd
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User git
      Banner none
  become: true

- name: Restart ssh
  service:
    name: ssh
    state: restarted
  become: true

  #############################
  # Init / Prepare install
  #############################

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become: true

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  become: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

  #############################
  # Install Docker
  #############################

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Upgrade packages
  apt:
    upgrade: "yes"
    update_cache: yes
    dpkg_options: "force-confold,force-confdef"
  become: true

- name: Dist-Upgrade
  apt:
    upgrade: "dist"
    dpkg_options: "force-confold,force-confdef"
  become: true