---
#############################
# Basic Initialization
#############################

#- name: Avoid displaying ssh banner on git ssh commands
#  blockinfile:
#    path: /etc/ssh/sshd_config
#    block: |
#      Match User git
#      Banner none

#- name: Restart ssh
#  service:
#    name: ssh
#    state: restarted
#  become: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: "yes"
    update_cache: yes
    dpkg_options: "force-confold,force-confdef"
  become: true

- name: Dist-Upgrade all packages to the latest version
  apt:
    upgrade: "dist"
    dpkg_options: "force-confold,force-confdef"
  become: true

#############################
# Basic Packages 
#############################
  
- name: "install basic packages" 
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - curl
    - nano
    - ltrace
    - ncdu
    - htop
    - net-tools
    - wget
    - unzip
    - python3
    - python3-venv 
    - python3-pip 
    # - linux-headers-$(uname -r)
    - build-essential
    - sudo
    - pkg-config
    - screen
    - ifupdown 
    - ufw
    - fail2ban
  become: true

#############################
# Custom env
#############################
- name: Debug Check ssh_usr variable
  debug:
    msg: ssh_usr = {{ ssh_usr }}

- name: Copy Bashrc
  copy:
    src: files/.bashrc
    dest: /home/{{ ssh_usr }}/.bashrc
    mode: 0644

- name: Copy Aliases
  copy:
    src: files/.aliases
    dest: /home/{{ ssh_usr }}/.aliases
    mode: 0644

